spring:
  jpa:
    database-plataform: com.example.sqlite.demosqlite.configuration.SQLiteDialect
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
